services:
  db:
    image: postgres:latest
    container_name: db_ex4
    env_file: .env
    secrets:
      - db_password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U john -d doe" ]
      interval: 5s
      timeout: 5s
      retries: 5

  debian_psql:
    build: ./debian_psql
    container_name: debian_psql
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true
    env_file: .env
    secrets:
      - db_password
    command: >
      bash -c "  echo 'Waiting for PostgreSQL...' &&  sleep 3 &&  export PGPASSWORD=$(cat /run/secrets/db_password) &&  export PGUSER=$${POSTGRES_USER} &&  export PGDATABASE=$${POSTGRES_DB} &&  export PGHOST=db &&  psql -h db -U $${PGUSER} -d $${PGDATABASE} -c 'SELECT NOW();' "

volumes:
  db_data:


secrets:
  db_password:
    file: ./db_password.txt
