services:
  db:
    image: postgres:latest
    container_name: db_ex3
    env_file: .env
    secrets:
      - db_password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:3232:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U john" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db_data:
secrets:
  db_password:
    file: ./db_password.txt
